// <auto-generated />
using System;
using IncomeTaxCalc.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeTaxCalc.Database.Migrations
{
    [DbContext(typeof(TaxCalcContext))]
    [Migration("20251003180719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncomeTaxCalc.Database.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("IncomeTaxCalc.Database.Models.TaxBand", b =>
                {
                    b.Property<int>("TaxBandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxBandId"));

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(6, 6)");

                    b.Property<decimal?>("UpperBound")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("TaxBandId");

                    b.HasIndex("RegionId");

                    b.ToTable("TaxBands");
                });

            modelBuilder.Entity("IncomeTaxCalc.Database.Models.TaxBand", b =>
                {
                    b.HasOne("IncomeTaxCalc.Database.Models.Region", "Region")
                        .WithMany("TaxBands")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("IncomeTaxCalc.Database.Models.Region", b =>
                {
                    b.Navigation("TaxBands");
                });
#pragma warning restore 612, 618
        }
    }
}
